/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package module;

import java.awt.HeadlessException;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author JayJomJohn
 */
public class Rental extends javax.swing.JFrame {

   Connection conn;
   ResultSet rs;
   PreparedStatement pst;
    public Rental() {
        initComponents();
        conn=JavaConnector.ConnecrDb();
        
        txtdate.setDateFormatString("MM/dd/yyyy");        
        txtduedate.setDateFormatString("MM/dd/yyyy");
        
        showload();
        disablebutton(); 
    }
void disablebutton(){
    txtcustid.setEnabled(false);
    txtcustomername.setEnabled(false);
    txtrentalfee.setEnabled(false);
    txtdate.setEnabled(false);
    txtduedate.setEnabled(false);
    
    
}
    
public void showload(){
    
  try {
      ResultSet rss;
            String sql ="select * from carregister";
            pst=conn.prepareStatement(sql);
            rss=pst.executeQuery(); 
            jComboBox1.removeAllItems();
            while(rss.next()) {
                String name =rss.getString(2);
                jComboBox1.addItem(name);
                    }
          }catch (Exception e){            
            JOptionPane.showMessageDialog(null, e);  
        } 
}    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtrentalfee = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        txtcustomername = new javax.swing.JTextField();
        txtduedate = new com.toedter.calendar.JDateChooser();
        txtcustid = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtdate = new com.toedter.calendar.JDateChooser();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        txtavail = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Rental");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Rental", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Due Date:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 140, 40));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Rental Fee:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 140, 40));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Car ID");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 140, 40));

        txtrentalfee.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(txtrentalfee, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 220, 230, 40));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Customer ID");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 140, 40));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Customer Name:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 140, 40));

        jComboBox1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, 110, 40));

        txtcustomername.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(txtcustomername, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, 230, 40));
        jPanel1.add(txtduedate, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 320, 230, 40));

        txtcustid.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtcustid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtcustidKeyPressed(evt);
            }
        });
        jPanel1.add(txtcustid, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, 230, 40));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Date:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 140, 40));
        jPanel1.add(txtdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 270, 230, 40));

        jButton2.setText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 370, 120, 40));

        jButton1.setText("Ok");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 370, 120, 40));

        txtavail.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(txtavail, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 70, 110, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 515, Short.MAX_VALUE)
                .addGap(41, 41, 41))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 449, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
      String car_id = jComboBox1.getSelectedItem().toString();
        try {
            String query = "SELECT * FROM carregister WHERE carno=?";
            pst=conn.prepareStatement(query);
            pst.setString(1,car_id);
            rs=pst.executeQuery();
            if(rs.next()==false){
                JOptionPane.showMessageDialog(rootPane,"Car No. Not Found!");
            }else{
                String aval = rs.getString("available");
                txtavail.setText(aval.trim());
                
                if(aval.equals("Yes")){
                    txtcustid.setEnabled(true);
                    txtcustomername.setEnabled(true);
                    txtrentalfee.setEnabled(true);
                    txtdate.setEnabled(true);
                    txtduedate.setEnabled(true);
                }else if(aval.equals("No"))
                    disablebutton();
            }
            
            
        } catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(rootPane,e);
        }
      
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void txtcustidKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcustidKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            String custid = txtcustid.getText();
            try {
                String query = "SELECT * FROM cus WHERE cust_id='"+custid+"'";
                pst=conn.prepareStatement(query);
                rs=pst.executeQuery();
                if(rs.next()==false){
                    JOptionPane.showMessageDialog(rootPane, "Customer No Not Found!");
                }else{
                    String custname=rs.getString("name");
                    txtcustomername.setText(custname.toUpperCase().trim());
                }
            } catch (Exception e) {
            }
        }
    }//GEN-LAST:event_txtcustidKeyPressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      int x = JOptionPane.showConfirmDialog(null, "Are You Sure You Want To Add Record?","AddRecord",JOptionPane.YES_NO_OPTION);
  if(x==0){ 
     
        String q1 = jComboBox1.getSelectedItem().toString();
        String q2 = txtcustid.getText();
        DateFormat df = new SimpleDateFormat("yyyy-MM-dd");
        String date = df.format(txtdate.getDate());
        String dates = df.format(txtduedate.getDate());
        String fee = txtrentalfee.getText();
        
        try {
            String query = "INSERT INTO rental(car_id,cust_id,fee,date,due)VALUES(?,?,?,?,?)";
            pst=conn.prepareStatement(query);
            pst.setString(1,q1);
            pst.setString(2,q2);
            pst.setString(3,fee);
            pst.setString(4,date);
            pst.setString(5,dates);          
            pst.execute();
            JOptionPane.showMessageDialog(rootPane,"Add Data Successfully!");
            
            String query2 = "UPDATE carregister SET available='No' WHERE carno=?";
            pst=conn.prepareStatement(query2);
            pst.setString(1,q1);
            pst.executeUpdate();
            JOptionPane.showMessageDialog(rootPane,"Update Data Successfully!");
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane,e);
        }
  }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      new Main().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Rental.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Rental.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Rental.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Rental.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Rental().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtavail;
    private javax.swing.JTextField txtcustid;
    private javax.swing.JTextField txtcustomername;
    private com.toedter.calendar.JDateChooser txtdate;
    private com.toedter.calendar.JDateChooser txtduedate;
    private javax.swing.JTextField txtrentalfee;
    // End of variables declaration//GEN-END:variables
}
