/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package module;

import java.awt.HeadlessException;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author JayJomJohn
 */
public class ReturnCar extends javax.swing.JFrame {

    Connection conn;
    ResultSet rs;
    PreparedStatement pst;
    public ReturnCar() {
        initComponents();
        conn=JavaConnector.ConnecrDb();
       
        showtable();
    }
   public final void showtable(){
        try {
            String sql = "SELECT * FROM returncar";
            pst=conn.prepareStatement(sql);
            rs=pst.executeQuery();
            jTable1.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (Exception e) {
        }
    } 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtcarid = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtcustomerid = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtdate = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtdayselapse = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtfine = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(514, 41, 440, 360));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Car ID:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 140, 30));

        txtcarid.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtcarid.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtcarid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtcaridKeyPressed(evt);
            }
        });
        getContentPane().add(txtcarid, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 70, 290, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Return Car");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, 150, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Customer ID:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 140, 30));

        txtcustomerid.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtcustomerid.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(txtcustomerid, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, 290, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Date:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 140, 30));

        txtdate.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtdate.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(txtdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 150, 290, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Days Elapse:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 140, 30));

        txtdayselapse.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtdayselapse.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(txtdayselapse, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, 290, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Fine:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 140, 30));

        txtfine.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtfine.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(txtfine, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 230, 290, 30));

        jButton1.setText("Cancel");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 270, 100, 40));

        jButton2.setText("Ok");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 270, 100, 40));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtcaridKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcaridKeyPressed
      if(evt.getKeyCode() == KeyEvent.VK_ENTER){
          try {
              String query = "SELECT car_id,cust_id,due,DATEDIFF(NOW(),due) as Elapse FROM rental WHERE car_id='"+txtcarid.getText()+"'";
              pst=conn.prepareStatement(query);
              rs=pst.executeQuery();
              if(rs.next()==false){
                  JOptionPane.showMessageDialog(rootPane,"Car ID Not Found!");
              }else{
                  String custid = rs.getString("cust_id");
                  txtcustomerid.setText(custid.trim());
                  
                  String date = rs.getString("due");
                  txtdate.setText(date.trim());
                  
                  String elp = rs.getString("elapse");
                  int elaped = Integer.parseInt(elp);
                  
                  if(elaped > 0){
                      txtdayselapse.setText(elp);
                      int fines = elaped * 100;
                      txtfine.setText(String.valueOf(fines));
                  }else{
                      txtdayselapse.setText("0");
                      txtfine.setText("0");
                  }
              }
              
          } catch (HeadlessException | NumberFormatException | SQLException e) {
            JOptionPane.showMessageDialog(rootPane,e);
          }
      }
    }//GEN-LAST:event_txtcaridKeyPressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new Main().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    int x = JOptionPane.showConfirmDialog(null, "Are You Sure You Want To Add Record?","AddRecord",JOptionPane.YES_NO_OPTION);
    if(x==0){     
        
        try {
            String sql ="INSERT INTO returncar(carid,custid,return_date,elap,fine)VALUES(?,?,?,?,?)";
            pst=conn.prepareStatement(sql);
            pst.setString(1,txtcarid.getText());
            pst.setString(2,txtcustomerid.getText());
            pst.setString(3,txtdate.getText());
            pst.setString(4,txtdayselapse.getText());
            pst.setString(5,txtfine.getText());
            pst.execute();
            
            String query2 = "UPDATE carregister SET available='Yes' WHERE carno='"+txtcarid.getText()+"'";           
            pst=conn.prepareStatement(query2);
            pst.executeUpdate();
            
            String sql3 = "DELETE FROM rental WHERE car_id ='"+txtcarid.getText()+"'";
            pst=conn.prepareStatement(sql3);
            pst.execute();
            
            JOptionPane.showMessageDialog(rootPane,"Car Updated Successfully");
            showtable();
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReturnCar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReturnCar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReturnCar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReturnCar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReturnCar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtcarid;
    private javax.swing.JTextField txtcustomerid;
    private javax.swing.JTextField txtdate;
    private javax.swing.JTextField txtdayselapse;
    private javax.swing.JTextField txtfine;
    // End of variables declaration//GEN-END:variables
}
